<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: addressbookv2.proto

namespace Addressbookv2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>addressbookv2.AddressBook</code>
 */
class AddressBook extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .addressbookv2.Person people = 1;</code>
     */
    private $people;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Addressbookv2\Person>|\Google\Protobuf\Internal\RepeatedField $people
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Addressbookv2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .addressbookv2.Person people = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPeople()
    {
        return $this->people;
    }

    /**
     * Generated from protobuf field <code>repeated .addressbookv2.Person people = 1;</code>
     * @param array<\Addressbookv2\Person>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPeople($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Addressbookv2\Person::class);
        $this->people = $arr;

        return $this;
    }

}

