<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: addressbookv2.proto

namespace Addressbookv2;

use UnexpectedValueException;

/**
 * Protobuf type <code>addressbookv2.PhoneType</code>
 */
class PhoneType
{
    /**
     * Generated from protobuf enum <code>PHONE_TYPE_UNSPECIFIED = 0;</code>
     */
    const PHONE_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>PHONE_TYPE_MOBILE = 1;</code>
     */
    const PHONE_TYPE_MOBILE = 1;
    /**
     * Generated from protobuf enum <code>PHONE_TYPE_HOME = 2;</code>
     */
    const PHONE_TYPE_HOME = 2;
    /**
     * Generated from protobuf enum <code>PHONE_TYPE_WORK = 3;</code>
     */
    const PHONE_TYPE_WORK = 3;

    private static $valueToName = [
        self::PHONE_TYPE_UNSPECIFIED => 'PHONE_TYPE_UNSPECIFIED',
        self::PHONE_TYPE_MOBILE => 'PHONE_TYPE_MOBILE',
        self::PHONE_TYPE_HOME => 'PHONE_TYPE_HOME',
        self::PHONE_TYPE_WORK => 'PHONE_TYPE_WORK',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

